name: "FRP Client (LEGACY)"
description: "You can use this tool to achieve remote access to local Home Assistant OS by port forwarding"
version: "1.0.1"
slug: "legacy_frpc"
host_network: true
startup: application
boot: "auto"
init: false
map:
  - "share:rw"
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  serverAddr: "example.com"
  serverPort: 7000
  customDomain: "example.com"
  proxyName: "homeassistant"
schema:
  serverAddr: str
  serverPort: int
  customDomain: str
  proxyName: str
