name: "FRP Client (LEGACY)"
description: "You can use this tool to achieve remote access to local Home Assistant OS by port forwarding"
version: "1.0.2"
slug: "legacy_frpc"
host_network: true
startup: application
boot: "auto"
init: false
map:
  - type: share
    read_only: false
  - type: ssl
    read_only: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  serverAddr: "example.com"
  serverPort: 7000
  proxyName: "homeassistant"
  proxyType: "tcp"
  localPort: 8123
  remotePort: 8123
  customDomain: "example.com"
  useEncryption: true
  useCompression: true
schema:
  serverAddr: str
  serverPort: int
  proxyName: str
  proxyType: str
  localPort: port
  remotePort: port
  customDomain: str
  useEncryption: bool
  useCompression: bool