serverAddr = "your_server_addr"
serverPort = 7000

log.to = "/share/frpc.log"
# trace, debug, info, warn, error
log.level = "trace"
log.maxDays = 3

[[proxies]]
name = "your_proxy_name"
type = "http"
customDomains = ["your_domain"]
transport.useEncryption = true
transport.useCompression = true
localPort = 8123
localIP = "0.0.0.0"
