serverAddr = "your.vps.ip.or.domain"
serverPort = 7000
auth.method = "token"
auth.token = "123456789"

log.to = "/share/frpc.log"
log.level = "info"
log.maxDays = 3

[[proxies]]
name = "homeassistant"
type = "http"
localIP = "127.0.0.1"
localPort = 8123
customDomains = ["home.silkslime.ru"]
transport.useEncryption = true
transport.useCompression = true
