name: "FRP Client"
version: "0.1.0"
slug: "frp_client"
description: "Reverse-proxy FRP client for Home Assistant"
startup: services
boot: auto

host_network: true

map:
  - share:rw
  - ssl:ro

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  serverAddr: "server.example.org"
  serverPort: 7000
  authMethod: "insecure"
  authToken: ""
  tlsEnable: true
  tlsCertFile: "/ssl/fullchain.pem"
  tlsKeyFile: "/ssl/privkey.pem"
  tlsCaFile: "/ssl/fullchain.pem"
  frpcConfig: |
    [[proxies]]
    name = "homeassistant"
    type = "http"
    localIP = "127.0.0.1"
    localPort = 8123
    customDomains = ["server.example.org"]
    transport.useEncryption   = true
    transport.useCompression  = true

schema:
  serverAddr: str
  serverPort: int
  authMethod: match(insecure|token)
  authToken: password
  tlsEnable: bool
  tlsCertFile: str
  tlsKeyFile: str
  tlsCaFile: str
  frpcConfig: str
