name: "FRP Client"
version: "1.1.0"
slug: "frp_client"
description: "Universal FRP client (HTTP & TCP) with TLS for Home Assistant"
startup: "services"
boot:    "auto"

# Изоляция и маунты
host_network: false
map:
  ssl: /ssl:ro     # подтягиваем сертификаты HA

arch:
  - aarch64
  - armv7
  - amd64
  - armhf
  - i386

options:
  # --- Основные параметры ---
  serverAddr:
    description: "IP или домен вашего FRPS (VPS)"
    type: string
    default: "vps.example.com"
  serverPort:
    description: "Порт FRPS для TCP-соединений"
    type: integer
    default: 7000

  authMethod:
    description: "Метод аутентификации"
    type: string
    default: "token"
    enum: ["token","insecure"]
  authToken:
    description: "Секретный токен (если token-auth)"
    type: string
    default: ""

  # --- TLS для FRP канала ---
  tlsEnable:
    description: "Шифровать канал FRP (TLS)"
    type: boolean
    default: true
  tlsCertFile:
    description: "Путь к клиентскому сертификату"
    type: string
    default: "/ssl/fullchain.pem"
  tlsKeyFile:
    description: "Путь к клиентскому ключу"
    type: string
    default: "/ssl/privkey.pem"
  tlsCaFile:
    description: "Путь к доверенному CA (обычно fullchain)"
    type: string
    default: "/ssl/fullchain.pem"

  # --- Ваши прокси-блоки (HTTP/TCP) ---
  frpcConfig:
    description: |
      Опишите здесь ваши [[proxies]]-блоки в TOML формате.
      Например, HTTP-прокси для HA и TCP-туннели:
    type: string
    default: |
      # HTTP-прокси Home Assistant
      [[proxies]]
      name = "homeassistant"
      type = "http"
      localIP = "127.0.0.1"
      localPort = 8123
      customDomains = ["home.silkslime.ru"]
      transport.useEncryption = true
      transport.useCompression = true

      # TCP-туннели
      [[proxies]]
      name = "open-webui"
      type = "tcp"
      localIP = "open-webui"
      localPort = 8080
      remotePort = 8080

      [[proxies]]
      name = "ollama"
      type = "tcp"
      localIP = "ollama"
      localPort = 11434
      remotePort = 11434

      [[proxies]]
      name = "automatic1111"
      type = "tcp"
      localIP = "automatic1111"
      localPort = 7860
      remotePort = 7860

schema:
  serverAddr:
    type: str
  serverPort:
    type: int
  authMethod:
    type: str
    enum: ["token","insecure"]
  authToken:
    type: str
  tlsEnable:
    type: bool
  tlsCertFile:
    type: str
  tlsKeyFile:
    type: str
  tlsCaFile:
    type: str
  frpcConfig:
    type: str
