name: "FRP Client"
version: "0.2.7"
slug: "frp_client"
description: "Reverse-proxy FRP client for Home Assistant using frpc"
startup: services
boot: auto
init: false
host_network: true

map:
  - type: share
    read_only: false
  - type: ssl
    read_only: true

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  serverAddr: "11.22.33.44"
  serverPort: 7000
  authMethod: "token"
  authToken: "secret-token"
  tlsEnable: true
  tlsCertFile: "/ssl/fullchain.pem"
  tlsKeyFile: "/ssl/privkey.pem"
  tlsCaFile: "/ssl/fullchain.pem"
  proxies:
    - name: "homeassistant"
      type: "http"
      localIP: "127.0.0.1"
      localPort: 8123
      remotePort: 8123
      customDomains:
        - "home.example.com"
      useEncryption: true
      useCompression: true

schema:
  serverAddr: str
  serverPort: int
  authMethod: match(insecure|token)
  authToken: password
  tlsEnable: bool
  tlsCertFile: str
  tlsKeyFile: str
  tlsCaFile: str
  proxies:
    - name: str
      type: match(http|tcp|udp)
      localIP: str
      localPort: port
      remotePort: port
      customDomains:
        - str
      useEncryption: bool
      useCompression: bool
