name: "FRP Client"
version: "0.1.0"
slug: "frp_client"
description: "Reverse-proxy FRP client for Home Assistant"
startup: services
boot: auto

host_network: true

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  serverAddr: ""            # заполните вашим VPS / FRPS адресом
  serverPort: 7000          # порт FRPS (TCP)
  authMethod: "token"       # или "insecure"
  authToken: ""             # токен, если authMethod = token
  tlsEnable: true           # шифровать канал FRP
  tlsCertFile: "/ssl/fullchain.pem"
  tlsKeyFile:  "/ssl/privkey.pem"
  tlsCaFile:   "/ssl/fullchain.pem"
  frpcConfig: |
    # Прокси только для Home Assistant
    [[proxies]]
    name                 = "homeassistant"
    type                 = "http"
    localIP              = "127.0.0.1"
    localPort            = 8123
    customDomains        = ["home.silkslime.ru"]
    transport.useEncryption   = true
    transport.useCompression  = true

schema:
  serverAddr:    str
  serverPort:    int
  authMethod:    match(token|insecure)
  authToken:     password
  tlsEnable:     bool
  tlsCertFile:   str
  tlsKeyFile:    str
  tlsCaFile:     str
  frpcConfig:    str
