name: "FRP Client"
version: "1.1.0"
slug: "frp_client"
description: "Universal FRP client (HTTP & TCP) with TLS for Home Assistant"
startup: "services"
boot:    "auto"

host_network: false
map:
  ssl: /ssl:ro

arch:
  - aarch64
  - armv7
  - amd64
  - armhf
  - i386

# Только дефолты для опций — без description и enum/default
options:
  serverAddr: "vps.example.com"
  serverPort: 7000
  authMethod: "token"
  authToken: ""
  tlsEnable: true
  tlsCertFile: "/ssl/fullchain.pem"
  tlsKeyFile: "/ssl/privkey.pem"
  tlsCaFile: "/ssl/fullchain.pem"
  frpcConfig: |

    # Ваши [[proxies]]-блоки здесь…

# Описание, типы и ограничения в schema
schema:
  serverAddr:
    description: "IP или домен вашего FRPS (VPS)"
    type: str
  serverPort:
    description: "Порт FRPS для TCP-соединений"
    type: int
  authMethod:
    description: "Метод аутентификации"
    type: match(token|insecure)
  authToken:
    description: "Секретный токен (если token-auth)"
    type: password
  tlsEnable:
    description: "Шифровать канал FRP (TLS)"
    type: bool
  tlsCertFile:
    description: "Путь к клиентскому сертификату"
    type: str
  tlsKeyFile:
    description: "Путь к клиентскому ключу"
    type: str
  tlsCaFile:
    description: "Путь к доверенному CA (обычно fullchain)"
    type: str
  frpcConfig:
    description: |
      Опишите здесь ваши [[proxies]]-блоки в TOML формате.
      Например, HTTP-прокси для HA и TCP-туннели.
    type: str
