name: "FRP Client"
version: "2.0.0"
slug: "frp_client"
description: "Reverse-proxy FRP client for Home Assistant"
startup: services
boot: auto

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  serverAddr: ""
  serverPort: 7000
  authMethod: "insecure"
  authToken: ""
  tlsEnable: true
  tlsCertFile: "/ssl/fullchain.pem"
  tlsKeyFile: "/ssl/privkey.pem"
  tlsCaFile: "/ssl/fullchain.pem"
  frpcConfig: |  
    [[proxies]]
    name = "homeassistant"
    type = "http"
    localIP = "127.0.0.1"
    localPort = 8123
    customDomains = ["home.silkslime.ru"]
    transport.useEncryption   = true
    transport.useCompression  = true

schema:
  serverAddr: { type: str }
  serverPort: { type: int }
  authMethod: { type: match(insecure|token) }
  authToken: { type: password }
  tlsEnable: { type: bool }
  tlsCertFile: { type: str }
  tlsKeyFile: { type: str }
  tlsCaFile: { type: str }
  frpcConfig: { type: str }