name: "FRP Client"
description: "Reverse-proxy FRP client for Home Assistant"
version: "1.1.2"
slug: "frp_client"

startup: "services"
boot:    "auto"

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  serverAddr:    ""          # IP или домен FRPS
  serverPort:    7000        # Порт FRPS (TCP)
  authMethod:    "token"     # “token” или “insecure”
  authToken:     ""          # строка-токен, если authMethod=token
  tlsEnable:     true        # шифровать туннель FRP
  tlsCertFile:   "/ssl/fullchain.pem"
  tlsKeyFile:    "/ssl/privkey.pem"
  tlsCaFile:     "/ssl/fullchain.pem"
  # Ниже вставляете свой TOML-блок [[proxies]]
  frpcConfig: |
    # Пример: http-прокси Home Assistant
    [[proxies]]
    name                 = "homeassistant"
    type                 = "http"
    localIP              = "127.0.0.1"
    localPort            = 8123
    customDomains        = ["home.silkslime.ru"]
    transport.useEncryption   = true
    transport.useCompression  = true

schema:
  serverAddr:
    type: str
  serverPort:
    type: int
  authMethod:
    type: match(token|insecure)
  authToken:
    type: password
  tlsEnable:
    type: bool
  tlsCertFile:
    type: str
  tlsKeyFile:
    type: str
  tlsCaFile:
    type: str
  frpcConfig:
    type: str
